package Modelo;
// Generated 14-feb-2021 11:56:58 by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int sitio;
     private String nombre;
     private String apellidos;
     private String departamento;

    public Empleados() {
    }

	
    public Empleados(int sitio) {
        this.sitio = sitio;
    }
    public Empleados(int sitio, String nombre, String apellidos, String departamento) {
       this.sitio = sitio;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.departamento = departamento;
    }
   
    public Integer getSitio() {
        return this.sitio;
    }
    
    public void setSitio(Integer sitio) {
        this.sitio = sitio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    @Override
    public String toString() {
        return  "Sitio: " + sitio + ",  Nombre: " + nombre +
                ",  Apellidos: " + apellidos + ",  Departamento: " + departamento;
    }
    
    


    


}


