package Modelo;
// Generated 14-feb-2021 11:56:58 by Hibernate Tools 4.3.1



/**
 * Ordenadores generated by hbm2java
 */
public class Ordenadores  implements java.io.Serializable {


     private int sitio;
     private String placa;
     private String procesador;
     private String tarjetaGrafica;
     private String memoriaRam;
     private String alimentacion;
     private String discoDuro;
     private String discoSsd;
     private String ventilacion;

    public Ordenadores() {
    }

    public Ordenadores(int sitio) {
        this.sitio = sitio;
    }
    public Ordenadores(int sitio, String placa, String procesador, String tarjetaGrafica, String memoriaRam, String alimentacion, String discoDuro, String discoSsd, String ventilacion) {
       this.sitio = sitio;
       this.placa = placa;
       this.procesador = procesador;
       this.tarjetaGrafica = tarjetaGrafica;
       this.memoriaRam = memoriaRam;
       this.alimentacion = alimentacion;
       this.discoDuro = discoDuro;
       this.discoSsd = discoSsd;
       this.ventilacion = ventilacion;
    }

   
    public int getSitio() {
        return this.sitio;
    }
    
    public void setSitio(int sitio) {
        this.sitio = sitio;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getProcesador() {
        return this.procesador;
    }
    
    public void setProcesador(String procesador) {
        this.procesador = procesador;
    }
    public String getTarjetaGrafica() {
        return this.tarjetaGrafica;
    }
    
    public void setTarjetaGrafica(String tarjetaGrafica) {
        this.tarjetaGrafica = tarjetaGrafica;
    }
    public String getMemoriaRam() {
        return this.memoriaRam;
    }
    
    public void setMemoriaRam(String memoriaRam) {
        this.memoriaRam = memoriaRam;
    }
    public String getAlimentacion() {
        return this.alimentacion;
    }
    
    public void setAlimentacion(String alimentacion) {
        this.alimentacion = alimentacion;
    }
    public String getDiscoDuro() {
        return this.discoDuro;
    }
    
    public void setDiscoDuro(String discoDuro) {
        this.discoDuro = discoDuro;
    }
    public String getDiscoSsd() {
        return this.discoSsd;
    }
    
    public void setDiscoSsd(String discoSsd) {
        this.discoSsd = discoSsd;
    }
    public String getVentilacion() {
        return this.ventilacion;
    }
    
    public void setVentilacion(String ventilacion) {
        this.ventilacion = ventilacion;
    }

    @Override
    public String toString() {
        return "Sitio: " + sitio + ",  Placa: " + placa + ",  Procesador: " + procesador +
                ",  TarjetaGrafica: " + tarjetaGrafica + ",  MemoriaRam: " + memoriaRam + 
                ",  Alimentacion: " + alimentacion + ",  DiscoDuro: " + discoDuro + ",  DiscoSsd: "
                + discoSsd + ",  Ventilacion: " + ventilacion;
    }




}


